### ISSUE TITLE
Homepage: Aligning inspirational quotes

### ISSUE THREAD

**Issue by apicii** [clarissakuemhof/MWC_HikeUnite#16]
sometimes the quote is center aligned and sometimes not. quote much bigger and italic maybe with ""

Also could add a frame for the quote and some other nice things for example like this:

![image](https://github.com/clarissakuemhof/MWC_HikeUnite/assets/80117157/585a5f2a-15ff-4948-891c-311a7dcdd3c4)

**Comment by clarissakuemhof** [comment]
<img width="289" alt="Bildschirmfoto 2023-12-06 um 09 56 53" src="https://github.com/clarissakuemhof/MWC_HikeUnite/assets/100838573/e90b7e04-af3a-45b2-8fff-c65acb91f745">
